version: '3.8'

services:
  japap-scraper:
    build: .
    container_name: japap-scraper
    restart: unless-stopped

    environment:
      # Base de données (à configurer)
      DATABASE_URL: ${DATABASE_URL}

      # Configuration scraping
      SCRAPING_INTERVAL: ${SCRAPING_INTERVAL:-0 */2 * * *}
      MAX_ARTICLES_PER_SOURCE: ${MAX_ARTICLES_PER_SOURCE:-20}
      RUN_ON_START: ${RUN_ON_START:-true}
      REQUEST_TIMEOUT: ${REQUEST_TIMEOUT:-30000}

      # Optionnel : Backend API pour intégration images
      BACKEND_API_URL: ${BACKEND_API_URL:-http://localhost:4000}
      BACKEND_API_KEY: ${BACKEND_API_KEY}

      # Optionnel : Stockage O2switch
      O2SWITCH_STORAGE_URL: ${O2SWITCH_STORAGE_URL}
      O2SWITCH_API_KEY: ${O2SWITCH_API_KEY}

    # Volumes pour logs persistants (optionnel)
    volumes:
      - ./logs:/app/logs

    # Network (si connecté à d'autres services JAPAP)
    networks:
      - japap-network

    # Logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  japap-network:
    # Utiliser le réseau externe si déjà créé pour autres services JAPAP
    external: true
    # Ou créer un nouveau réseau
    # driver: bridge
